version: "3"

services:
  airflow-sandbox:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - AIRFLOW_HOME=/usr/local/airflow
    command: webserver -p 8080
    ports:
      - 8080:8080
    volumes:
      - ./dags/:/usr/local/airflow/dags/
